---
title: Mi Blog
timezone: America/Buenos_Aires
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mau.cendon@gmail.com
description: 'Blog de Mauro Cendón

'
baseurl: ''
url: ''
twitter_username: maucendon
github_username: mcendon
markdown: kramdown
theme: jekyll-theme-cayman
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
