---
title: Blog de Mauro Cendón
timezone: America/Buenos_Aires
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mau.cendon@gmail.com
description: 'Blog de Mauro Cendón'
disqus:
  shortname: 'blog-de-mauro-cendon-1'
baseurl: ''
url: ''
twitter_username: maucendon
github_username: mcendon
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
